### ISSUE TITLE
Allow for arbitrary body content

### ISSUE THREAD

**Issue by Wavesonics** [oRRs/mdl-jquery-modal-dialog#4]
It would be nice to be able to specify some arbitrary HTML to be displayed in the dialog.

**Comment by odama626** [comment]
you can

```
showDialog({
 title: 'title',
text: `
   <div>Some arbitrary content</div>
`
});
```

you can also use the onLoaded callback to use JS on the body after its loaded into the dom

**Comment by Wavesonics** [comment]
oh cool, thanks!
