### ISSUE TITLE
Add concept of an icon

### ISSUE THREAD

**Issue by Wavesonics** [oRRs/mdl-jquery-modal-dialog#5]
Sweet Alert's built in icons are pretty great. And you can override them with your own if you like:
http://t4t5.github.io/sweetalert/

Adding some default material icons for success, failure, info, would be great.

And really just having the concept of an icon in general at the top left of the dialog would be nice.

**Comment by oRRs** [comment]
Thanks for your request!
Unfortunately, MDL 1.x seems to have reached its end of life and will be replaced by https://github.com/material-components/material-components-web.
So I'm not planning to implement new features for this add-on, sorry!
